name: 'Create a Release'
description: 'Create a release for a tag in your repository'
author: 'GitHub'
inputs:
  template:
    description: 'Mustache template file for release body'
    required: true
  title:
    description: 'The name of the release. For example, `Release v1.0.1`'
    required: true
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
    required: false
    default: 'false'
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`'
    required: false
    default: 'false'
outputs:
  id:
    description: 'The ID of the created Release'
  url:
    description: 'The URL users can navigate to in order to view the release'
runs:
  using: 'node12'
  main: 'main.js'
branding:
  icon: 'tag'
  color: 'gray-dark'