name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch test.deb
        env:
          TEST_DATA: "Hello world"
          TEST_LINK: "https://github.com"
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test.deb
      - uses: ./
        with:
          title: Hello world
          template: test.md
          token: ${{ secrets.GITHUB_TOKEN }}
          variables: '{"data": "Hello world!", "link": "https://github.com"}'
